### ISSUE TITLE
[Feature Request] There's a way to improve a pagination?

### ISSUE THREAD

**Issue by sylvilag** [barbushin/php-imap#362] opened 2019-07-07 18:52 UTC
With the current version, there is a way to make a pagination to gain performance loading only x messages at a time?

Sorry by my bad english.

**Comment by Sebi94nbg** [comment] 2019-07-09 09:21
Duplicate of #107.

No, there is currently no built-in support for pagination. This is currently something, what you need to handle with your own PHP code logic.

**Closed by Sebi94nbg** 2019-07-09 09:21 UTC
Labels: needs investigation
