### ISSUE TITLE
Getting 'iconv(): Detected an incomplete multibyte character in input string'

### ISSUE THREAD

**Issue by RomanBurunkov** [barbushin/php-imap#265] opened 2018-09-20 15:23 UTC
Hi there,

I'm currently use version about 2.0.5...not sure which exactly because can't find version number in source code.

Quite often gets this error message during getting emails:

```
PhpImap/Mailbox.php; 628; iconv(): Detected an incomplete multibyte character in input string
```

At 628 row I got the following code:
```
	protected function convertStringEncoding($string, $fromEncoding, $toEncoding) {
		$convertedString = null;
		if($string && $fromEncoding != $toEncoding) {
			$convertedString = @iconv($fromEncoding, $toEncoding . '//IGNORE', $string);
			if(!$convertedString && extension_loaded('mbstring')) {
				$convertedString = @mb_convert_encoding($string, $toEncoding, $fromEncoding);
			}
		}
		return $convertedString ?: $string;
	}
```

I've tried to use convertStringEncoding from latest version:
```
	/**
	 * Converts a string from one encoding to another.
	 * @param string $string
	 * @param string $fromEncoding
	 * @param string $toEncoding
	 * @return string Converted string if conversion was successful, or the original string if not
	 * @throws Exception
	 */
	protected function convertStringEncoding($string, $fromEncoding, $toEncoding) {
		if(!$string || $fromEncoding == $toEncoding) {
			return $string;
		}
		$convertedString = function_exists('iconv') ? @iconv($fromEncoding, $toEncoding . '//IGNORE', $string) : null;
		if(!$convertedString && extension_loaded('mbstring')) {
			$convertedString = @mb_convert_encoding($string, $toEncoding, $fromEncoding);
		}
		if(!$convertedString) {
			throw new Exception('Mime string encoding conversion failed');
		}
		return $convertedString;
	}
```

But still got the same issue.

Is there any way to fix that?

**Comment by Sebi94nbg** [comment] 2019-05-09 19:28
I've added a PHPUnit test. See referenced commit.

I can not reproduce this issue. Closing this for now since it's already really old.

I'll reopen this issue when you or somebody else can provide some example strings, which are causing this issue.

You also can open a new issue, if you want to.

**Closed by Sebi94nbg** 2019-05-09 19:28 UTC
Labels: needs investigation, phpunit
