### ISSUE TITLE
some email can't parse body

### ISSUE THREAD

**Issue by helloHupc** [barbushin/php-imap#312] opened 2019-05-08 06:46 UTC
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.5
 - PHP Version: 7.2
 - Type of execution:

**Your Text**
I met a situation that some normal email can't parse body. the textHtml is NULL and the plainHtml is NULL also.

there is one of that exception emails' partStructure:

{"type":1,"encoding":0,"ifsubtype":1,"subtype":"MIXED","ifdescription":0,"ifid":0,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"boundary","value":"----=_001_NextPart276727435753_=----"}],"parts":[{"type":1,"encoding":0,"ifsubtype":1,"subtype":"ALTERNATIVE","ifdescription":0,"ifid":0,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"boundary","value":"----=_002_NextPart104486840068_=----"}],"parts":[{"type":0,"encoding":3,"ifsubtype":1,"subtype":"PLAIN","ifdescription":0,"ifid":0,"lines":13,"bytes":954,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"charset","value":"GB2312"}]},{"type":0,"encoding":4,"ifsubtype":1,"subtype":"HTML","ifdescription":0,"ifid":0,"lines":96,"bytes":7400,"ifdisposition":0,"ifdparameters":0,"ifparameters":1,"parameters":[{"attribute":"charset","value":"GB2312"}]}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":954602,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMS5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMS5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1295030,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMi5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMi5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1826224,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMy5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMy5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1265572,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNC5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNC5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2052882,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNS5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNS5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1192884,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNi5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNi5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1778016,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtNy5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtNy5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1541670,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtOC5wZGY=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtOC5wZGY=?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1214116,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTAucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTAucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1357254,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTEucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTEucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1663096,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTIucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTIucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2328112,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTMucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTMucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2003748,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTQucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTQucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2176566,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTUucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTUucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1315660,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTYucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTYucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":1298680,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTcucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTcucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":2247640,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?yfPF+rHtMTgucGRm?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?yfPF+rHtMTgucGRm?="}]},{"type":3,"encoding":3,"ifsubtype":1,"subtype":"OCTET-STREAM","ifdescription":0,"ifid":0,"bytes":34690,"ifdisposition":1,"disposition":"attachment","ifdparameters":1,"dparameters":[{"attribute":"filename","value":"=?GB2312?B?vfW9rdau0MdFz+7Evy25qdOmyczJ6sfrse1WMi4wLnhsc3g=?="}],"ifparameters":1,"parameters":[{"attribute":"name","value":"=?GB2312?B?vfW9rdau0MdFz+7Evy25qdOmyczJ6sfrse1WMi4wLnhsc3g=?="}]}]}

**Comment by Sebi94nbg** [comment] 2019-05-08 09:32
@helloHupc Please update your php-imap library to the latest release 3.0.12 and try it again.

**Comment by Sebi94nbg** [comment] 2019-05-08 09:40
Closing this as it's a duplicate of #198. Please continue in the referenced issue.

**Closed by Sebi94nbg** 2019-05-08 09:40 UTC
