### ISSUE TITLE
[ENHANCEMENT] searchMailbox() could not search Chinese subject

### ISSUE THREAD

**Issue by mountainguan** [barbushin/php-imap#250] opened 2018-06-13 07:12 UTC
I just using this class to build an easy email client. But when I using searchMailBox function, only English keyword could return a result. Chinese subject can not be search. 

For example, my email subject is "mountainguan测试":
```
$mailbox->searchMailbox('SUBJECT "mountainguan"');// it work
$mailbox->searchMailbox('SUBJECT "测试"');// it doesn't work
```

**Comment by yellow1912** [comment] 2018-12-21 03:43
Just saw this but perhaps setting the charset will help?

http://php.net/imap_search

<?php imap_search($inbox,'BODY "'.$keyword.'"', SE_FREE, "UTF-8"); ?>

**Comment by Sebi94nbg** [comment] 2019-05-03 23:32
This library can not find the email as initially described here, but testing it directly via the `openssl` client works fine:
```bash
openssl s_client -connect <mailserver>:993

a LOGIN <user> <pass>
a OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA] Logged in


a SELECT "inbox"
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft unknown-0 unknown-1 $NotJunk $Forwarded)
* OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft unknown-0 unknown-1 $NotJunk $Forwarded \*)] Flags permitted.
* 9 EXISTS
* 0 RECENT
* OK [UNSEEN 9] First unseen.
* OK [UIDVALIDITY 1500057051] UIDs valid
* OK [UIDNEXT 5388] Predicted next UID
* OK [HIGHESTMODSEQ 14790] Highest
a OK [READ-WRITE] Select completed (0.000 + 0.000 secs).


a UID SEARCH SUBJECT "mountain"
* SEARCH 5387
a OK Search completed (0.001 + 0.000 secs).


a UID SEARCH SUBJECT "测试"
* SEARCH 5387
a OK Search completed (0.001 + 0.000 secs).


a UID FETCH 5387 (BODY[HEADER.FIELDS (subject date)])
* 9 FETCH (UID 5387 FLAGS (\Seen) BODY[HEADER.FIELDS (SUBJECT DATE)] {245}
Subject: =?UTF-8?Q?mountainguan=E6=B5=8B=E8=AF=95?=
Date: Sat, 4 May 2019 01:11:57 +0200

)
a OK Fetch completed (0.001 + 0.000 secs).


a logout
* BYE Logging out
a OK Logout completed (0.000 + 0.000 secs).
closed
```

ToDo: Why is the same search on the same server not working with `php-imap`?

**Comment by Sebi94nbg** [comment] 2019-06-01 19:12
I've played around with the IMAP search and tried a lot of things, but I couldn't figure out, why the same search is not working in `php-imap`, while it is working with OpenSSL.

At least, I know now, that it's not a bug in the `php-imap` library as I also have this issue in a simple and clean PHP script, which is just using the PHP imap functions as they are.

I've asked this question in the Stackoverflow community: https://stackoverflow.com/questions/56409639/php-imap-search-search-utf-8-non-ascii-characters-with-utf-8-support

Hopefully, somebody has an answer.

**Comment by Sebi94nbg** [comment] 2020-05-29 15:13
Merged the fix into `develop`! I'll release a new `master` version approx. on this Sunday.

**Closed by Sebi94nbg** 2020-05-29 15:13 UTC
Labels: enhancement, need help, needs investigation
