### ISSUE TITLE
[BUG] getMail returns hasAttachments false when there are attachments?

### ISSUE THREAD

**Issue by yuliangruan** [barbushin/php-imap#478] opened 2020-02-12 01:42 UTC
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.33
 - PHP Version: PHP 7.2.24-0ubuntu0.18.04.1 (cli)
 - Type of execution: cli

**Describe the bug**
I have a outlook email that I can see has attachment however getMail() returns hasAttachments=false, leading rest of code to not process for an attachment

**To Reproduce**
Steps to reproduce the behavior.

The used code:
```php
$messageId = '<MWHPR08MB3326D5B7A86A0CA7D3D0192D88010@MWHPR08MB3326.namprd08.prod.outlook.com>';

$mailbox=new PhpImap\Mailbox(
                '{imap-mail.outlook.com:993/imap/ssl}', // IMAP server and mailbox folder
                'yuliang.ruan@hotmail.com', // Username for the before configured mailbox
                'dummypass', // Password for the before configured username
                './attachments'// Directory, where attachments will be saved (optional),
            );

$mail=$mailbox->getMail($messageId);

var_dump($mail);
```

The headers of the parsed email, if required and possible (only, if it's NOT confidential):
```
Received: from CO1NAM11HT255.eop-nam11.prod.protection.outlook.com
(2603:10b6:300:ed::32) by MWHPR08MB3326.namprd08.prod.outlook.com with HTTPS
via MWHPR20CA0046.NAMPRD20.PROD.OUTLOOK.COM; Sun, 2 Feb 2020 17:40:32 +0000
ARC-Seal: i=2; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=pass;
b=ochYdWD6hHXoAI4vFdAGxJ4Uu0B1HjvbJJ/n5ABaRoHXb8NyNT/Wv3XMskKJs3VA4eYX1AgOS33YvjkQCkL6rlLBAY2eJyWS7raLR6TkBh/1cvC51MWmPXa3Co5Ud7uCeawj7YX1AxHGj+CvFS0pNXJat+p3sRcx5vAjpbylCM8nCW9lkiQGXMbJpBL804aWIlYjsomFs/j2aDg41dAu8SnVL87OQ/HhrHV+J0AimjW/u79pzfqqq6V8k3ydZNrQZ1c9CWiR3Yu284W1HtefO7kg0VFbaboxyAZHlBXvFgR2RlP1MkcqW1XKGJ3LOi0Za+IKwgXS0Ks4+XY9lpQ+tw==
ARC-Message-Signature: i=2; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
s=arcselector9901;
h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
bh=gioJc+unHmAEg0P11FNVdBw9Nv/4gFzzX7uwEmNjYsU=;
b=DGsvFfyYtok/LU2DSAbz1gVhDdlPiXWXGPDroB02YcZGfDlVydZq8FWaEr0D9uDvB2MFHEBjZzu8QZW6zQtZA5BcMIgC2gWUkyRfAVqw6m2FG+uUQKLrFTmxd1Smt4AXVbYkOCANkjATdVZp2aLtrqmO0Xu/osRNR/BkYqfFgImUNeAPMHcFxjpKV/V3Oo3wWN+iDElUnP9JtPAaS2NV9YyZ7PFlVrYirgH6ykMkvg1QFDpz7tgx49J39pa+WrGxvzEgtpu0/SRf/wR+x9wU8bnJ/zMaN7btL/qDpr0h9ZM5nrKeDTLND8lIsWYb/3oDcCQ4e59UtZ39wfAVHEgT4w==
ARC-Authentication-Results: i=2; mx.microsoft.com 1; spf=pass (sender ip is
40.92.20.70) smtp.rcpttodomain=hotmail.com smtp.mailfrom=hotmail.com;
dmarc=pass (p=none sp=none pct=100) action=none header.from=hotmail.com;
dkim=pass (signature was verified) header.d=hotmail.com; arc=pass (0 oda=0
ltdi=1)
Received: from CO1NAM11FT040.eop-nam11.prod.protection.outlook.com
(10.13.174.51) by CO1NAM11HT255.eop-nam11.prod.protection.outlook.com
(10.13.175.135) with Microsoft SMTP Server (version=TLS1_2,
cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2686.25; Sun, 2 Feb
2020 17:40:29 +0000
Authentication-Results: spf=pass (sender IP is 40.92.20.70)
smtp.mailfrom=hotmail.com; hotmail.com; dkim=pass (signature was verified)
header.d=hotmail.com;hotmail.com; dmarc=pass action=none
header.from=hotmail.com;compauth=pass reason=100
Received-SPF: Pass (protection.outlook.com: domain of hotmail.com designates
40.92.20.70 as permitted sender) receiver=protection.outlook.com;
client-ip=40.92.20.70; helo=NAM11-BN8-obe.outbound.protection.outlook.com;
Received: from NAM11-BN8-obe.outbound.protection.outlook.com (40.92.20.70) by
CO1NAM11FT040.mail.protection.outlook.com (10.13.174.140) with Microsoft SMTP
Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
15.20.2686.25 via Frontend Transport; Sun, 2 Feb 2020 17:40:28 +0000
X-IncomingTopHeaderMarker:
OriginalChecksum:BC06023A843B73836C517012E681E739B9E21F1D69677504B7D10DCBE35EC46F;UpperCasedChecksum:A154F6A9EEFDA6E68330D5C2FEC9036BAB2EB66D68A6E62728560C9560F7D367;SizeAsReceived:5129;Count:40
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
b=nd63621gzCgmIfDHvKAaPBG33HSzTGAJw/1PzBLnhr72snJBuzH+jyKNO1cJjhIctVEjU/bYMCFj7SMvkdFJIoiEfxreGyNCXSqzhY6SginmEti+QS4+hWYUy1KuFtUyG1YPJ4J5ScKr8xb1rG/ChJxhojkPPI8gHMKuKWwUzsxe65ru4NXZI6ZqTW6NccVA+lucpLmyAWKF0Hd2BpK/SnIin4gvG3ClElu1yuubxPpvgHPosWzPHXoWeL01jx+MaG9D3CDRAWzHF2dqjS5bdqofnhSADFuXedpF7s/JNXK5LmwrI6L+EQ6rmVznfyFwYp+gcPhvCSTelDtJWIq7ig==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
s=arcselector9901;
h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
bh=gioJc+unHmAEg0P11FNVdBw9Nv/4gFzzX7uwEmNjYsU=;
b=iZF8crBV8mVUgxf/yhusk0BiKVqnabaDrRzGaL/UIXvuAyItwwtstDAnIkVGa83IxmnnGT92akhZp38abg8CFp5ZivUjYp2RKyEjHVz5e9x685IZq5TkEbOHFSvIrzP6JOup4FakBdLIDanxCFgm1HIXuXK6veVFmvYliTJSxDKhG1MQY33NROoqSUwB0RD999mUh982XHSTS8LimrkzU5+/mkEH2SxV0uot1XDSMlAxXqYfiVduCT0+3QiFn0ukamIXC87Di9f0qIsgbR6uld64I0QoP+peBOzhn6iLhVTfmp6NsA/TqRfL2Q0usY/17M1muehC3KUOdm6kKg5ssA==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=none; dmarc=none;
dkim=none; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=hotmail.com;
s=selector1;
h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
bh=gioJc+unHmAEg0P11FNVdBw9Nv/4gFzzX7uwEmNjYsU=;
b=GZGWPtV421otj/aBndmvkkaQ/oyjjWM1XEurJ7YYPSkEX66fLvTBc8V1M0wSUQhPvaSM97AJKSOkK/qYIb6KFQzqC4ADMRTIIDv0oEdmQLiCI2ZstpFK39kLbM+9k57ns3J1idGtU/84UG7XyepasOCsdpwE2PFtxphOmqV5b8PRvDkfm9hGgBipgRLIh1Qefkq9V8y2ZZAQoN4qmPVae1XWXoEDBtCkeEHCADAMI2rQc3XOy0W+vnOWGVz4cuRB3NjRfunvGuJ96Ypnq4z91EkzUUm703Ubjg/avYHPMItYCb8wGFTENaS/JIMPOu+xxtfeO3TDXy19KzxuldZrHQ==
Received: from BN8NAM11FT005.eop-nam11.prod.protection.outlook.com
(10.13.176.57) by BN8NAM11HT202.eop-nam11.prod.protection.outlook.com
(10.13.177.50) with Microsoft SMTP Server (version=TLS1_2,
cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2686.25; Sun, 2 Feb
2020 17:40:26 +0000
Received: from MWHPR08MB3326.namprd08.prod.outlook.com (10.13.176.53) by
BN8NAM11FT005.mail.protection.outlook.com (10.13.176.69) with Microsoft SMTP
Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
15.20.2686.25 via Frontend Transport; Sun, 2 Feb 2020 17:40:26 +0000
Received: from MWHPR08MB3326.namprd08.prod.outlook.com
([fe80::a59f:ea1b:3b04:1410]) by MWHPR08MB3326.namprd08.prod.outlook.com
([fe80::a59f:ea1b:3b04:1410%6]) with mapi id 15.20.2686.031; Sun, 2 Feb 2020
17:40:25 +0000
From: yuliang ruan <yuliang.ruan@hotmail.com>
To: yuliang ruan <yuliang.ruan@hotmail.com>
Subject: waht?? attachment??
Thread-Topic: waht?? attachment??
Thread-Index: AQHV2e/XMCuO/ZnvkkKZgapBRu2Xrg==
Date: Sun, 2 Feb 2020 17:40:25 +0000
Message-ID:
<MWHPR08MB3326D5B7A86A0CA7D3D0192D88010@MWHPR08MB3326.namprd08.prod.outlook.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-TNEF-Correlator:
x-incomingtopheadermarker:
OriginalChecksum:30D508D762B7E62AC8771C1FFB4CF45E6AE8DA8BD2DE8F7B7AEA1CFCB258D809;UpperCasedChecksum:0F9CD61B05587AFFEC868B46BABAC340506644BE63730C5292EFA88341926226;SizeAsReceived:6656;Count:42
x-tmn: [Cxuj9d8DCivW+MlqoMkCJAa8qfGuauKe]
x-ms-publictraffictype: Email
x-incomingheadercount: 42
x-eopattributedmessage: 1
X-MS-Office365-Filtering-Correlation-Id: 02a1cbe1-bb74-470a-664b-08d7a806fea5
x-ms-exchange-slblob-mailprops:
eHqJcHuqIyh5g7Td9/E9AbvFf1rPJMPnJatJuO6RWSjO0qWISCReAvvmJuI916GOKtDcB3ED3e1zqLK0KLjS/LhslWN214j1Q2i2GgFO2A3Rh96PUkMWQK/AqSJpCnAHCdD6gAg7Os2MW1x+VJfaDQ0WYrcYsqczRnoueBlvAjJu4klX1D6GZQBoZVAFrczOVGH8JygpRjyl36SDrzh/unpsBx/gyU8QxlP53Przqhecp+DZGvnq8yN3Z0TTijFPH/cXg/2cE1+znfhpMKftMdjyNDeT9f+kGxwHvKBf5kmqjDa+VwDnRmH1DHsin08N/X2AMExExvF3iZ3FYc2f7gJPzm/7qBYjloljdg16IlJ0IbDciUP15vxgAtJngvVUvOd6GKilhSBFLeoOXkZP8MjXsqZGOC4uQMguHOJzrXQ9eRuXFcEBYf/zheny8pimteqFFdZKRODwM7Ggr9jmxKFDCtC2sKc/9/WA3bsTvpcQhLVk32j5WUGM/SZKvfQnwb6KJ/a/ZR5W8uBW3fn0YNvL8cO57aEAWheD5+iDpW2OlOaXgTO2+/qS9EIyKMvr1TgqhHkmsGRuIdhgRiPrBkrk9b4d3m5bSK+HGYuPnCY=
X-MS-TrafficTypeDiagnostic: BN8NAM11HT202:|CO1NAM11HT255:
X-Microsoft-Antispam-Untrusted: BCL:0;
X-Microsoft-Antispam-Message-Info-Original:
QZsKQD3M1jj0+WAK+oUgoGcmRu3/p5dbA99PJAIIiFt9cU6l19oHJVWEKklx/RRJ
x-ms-exchange-antispam-messagedata:
twC6w+tKXJpndpsUReRIS6ucz6ChNrtQtgWdue04AQ6OVHPFk5M21NslD3pJpSe2EgvBdUflaStSnydepJUqzpYuNKMEhUPY5OX8rC4r1guTIeD4WLBnOsy9cM0Wg9/l0DSnhfDJHpMXC7CbosNfIA==
x-ms-exchange-transport-forked: True
Content-Type: multipart/mixed;
boundary="_004_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_"
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BN8NAM11HT202
X-IncomingHeaderCount: 40
Return-Path: yuliang.ruan@hotmail.com
X-MS-Exchange-Organization-ExpirationStartTime: 02 Feb 2020 17:40:29.1737
(UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id:
02a1cbe1-bb74-470a-664b-08d7a806fea5
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-Exchange-Transport-CrossTenantHeadersStripped:
CO1NAM11FT040.eop-nam11.prod.protection.outlook.com
X-MS-Exchange-Transport-CrossTenantHeadersPromoted:
CO1NAM11FT040.eop-nam11.prod.protection.outlook.com
X-Forefront-Antispam-Report: EFV:NLI;
X-MS-Exchange-Organization-AuthSource:
CO1NAM11FT040.eop-nam11.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-UserLastLogonTime: 2/2/2020 5:40:01 PM
X-MS-Office365-Filtering-Correlation-Id-Prvs:
6b706d52-0e99-410c-3896-08d7a806fca2
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 40.92.20.70
X-SID-PRA: YULIANG.RUAN@HOTMAIL.COM
X-SID-Result: PASS
X-MS-Exchange-Organization-PCL: 2
X-Microsoft-Antispam: BCL:0;
X-OriginatorOrg: hotmail.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 02 Feb 2020 17:40:28.9890
(UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 02a1cbe1-bb74-470a-664b-08d7a806fea5
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-CrossTenant-rms-persistedconsumerorg: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: CO1NAM11HT255
X-MS-Exchange-Transport-EndToEndLatency: 00:00:03.2718196
X-MS-Exchange-Processed-By-BccFoldering: 15.20.2686.019
X-Microsoft-Antispam-Mailbox-Delivery:
dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:I;OFR:SpamFilterPass;ENG:(5062000261)(5061607266)(5061608174)(1004385)(4900115)(4920090)(6220004)(4950130)(4990090)(9110004);
X-Message-Info:
5vMbyqxGkdcyxtrjnyjQiyYBqKnVW2BKjAiuv3YNuFd4qPrP7mngCvD2FSmuZ2KBxipnqf4EPRvKX8wbBeaFsbZZex0ee593/3/R1NiANsinQocDXdUHLGQKDKwl8uRdbMkFR5raWtq15PKYr9EvxjYiFzxdzqYio8K6TwCUKQIwSG0Hzf6KE/LBmb68ZEcbOI7HB6qxL9/WvCETUP+RVQ==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0wO0Q9MTtHRD0yO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
GCZ6lEuiGeBDur4dCRaQ/dzM0UtE0BoWqiFpxGwybG/lOV4skS0a0ViRofaQ2W1V8o5691yeFEpPCP4UJr5QmUAtWyXRRKiy9WbuMNv1UHls52n1MVErvLjjaDc4IdQY7IQU6Q6/EQn1YIJXOvxwrihIsN0g48XhhTroa4rpdB414bYygfO2mi4YLHUE9I8IDGCJt5EI3GRtqCt/ebLW5X6SV3wlXHKqtollh1Nrsv3hrFzaIuvvzYYilwaW9xe7PDevBLpjFBlJaobPfDkuCFm3pCYnJJ4JWipMIv9GUDLMzjvKdhE+bRqn2wi4+SxmPlHpZXpiWjZ28ahShRaEIHOujmY69IMh+NebOUVxMvxvfm/W2f1guAsXNld89URfJ2Wp/+0R9R/M/T6rQW/bhYJjeou8tyzGnN6T90cPssh28Jvt9U98d6S4HpG9zduTmjYm/gmVLheC6fsX+8D6U8OXyJSSSPJYhEg3VtYQkBNfZAKN4MRiv8TDeFB8GBvBcRpwl+zPIHG94lSqS4YfEO7Es9cy02aWnNVCEoWtj6FBJRNP+21sCSQnNDzoh9VPFD/V+RSCmGB0spQVFTJrsM+VY3F7fvLW+k2jm4f4IBzbcCOegCE36LV1LE1bRdn7oA6jHGa+2JVtnVZo6geVueo5iygf5doWh+Pz5EeDc9xuENx6oG/Cyl5kmuESCC1/oQ5LeOuuDlG4WgFXsRBl263r1rrBmwSUJfyJNM2QY5pBUN4SIeg6Mj1RewVMoYnWixxULgMMvlKT1+liCYjs+DWKhdppinbbTn2/Sh0hePmH7GWmMmM6JlRtosUet7ZojHLqsjFZb367mbCsowkCX/6L+DOFRnbyEIqzuMBvKHU=
MIME-Version: 1.0

--_004_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_
Content-Type: multipart/alternative;
boundary="_000_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_"

--_000_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

ashtastas
aastas
htast
astast
astastastastasta
shtas
tast

--_000_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<style type=3D"text/css" style=3D"display:none;"> P {margin-top:0;margin-bo=
ttom:0;} </style>
</head>
<body dir=3D"ltr">
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
ashtastas</div>
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
aastas</div>
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
htast</div>
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
astast</div>
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
astastastastasta</div>
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
shtas</div>
<div style=3D"font-family: Calibri, Arial, Helvetica, sans-serif; font-size=
: 12pt; color: rgb(0, 0, 0);">
tast</div>
</body>
</html>

--_000_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_--

--_004_MWHPR08MB3326D5B7A86A0CA7D3D0192D88010MWHPR08MB3326namp_
Content-Type: application/vnd.ms-pki.stl; name="rose_open_printable.stl"
Content-Description: rose_open_printable.stl
Content-Disposition: attachment; filename="rose_open_printable.stl";
size=1111584; creation-date="Sun, 02 Feb 2020 17:40:23 GMT";
modification-date="Sun, 02 Feb 2020 17:40:25 GMT"
Content-Transfer-Encoding: base64

.......the attachment itself
```

**Expected behavior**
hasAttachment=true

**Screenshots / Outputs**

![image](https://user-images.githubusercontent.com/10715546/74295332-5df98e80-4d06-11ea-8cf9-7e5814a4d6dd.png)

root@b662e153678e:/app# php yr-minimal.php
PHP Notice:  Trying to get property 'encoding' of non-object in /app/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1032
PHP Notice:  Trying to get property 'type' of non-object in /app/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1054
PHP Notice:  Trying to get property 'subtype' of non-object in /app/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1063
PHP Notice:  Trying to get property 'type' of non-object in /app/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1107
PHP Notice:  Trying to get property 'type' of non-object in /app/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1115
object(PhpImap\IncomingMail)#2 (27) {
  ["attachments":protected]=>
  array(0) {
  }
  ["hasAttachments":protected]=>
  bool(false)
  ["dataInfo":protected]=>
  array(2) {
    [0]=>
    array(0) {
    }
    [1]=>
    array(0) {
    }
  }
  ["id"]=>
  string(80) "<MWHPR08MB3326D5B7A86A0CA7D3D0192D88010@MWHPR08MB3326.namprd08.prod.outlook.com>"
  ["isDraft"]=>
  bool(true)
  ["date"]=>
  string(25) "2020-02-11T17:51:47-06:00"
  ["headersRaw"]=>
  NULL
  ["headers"]=>
  object(stdClass)#4 (0) {
  }
  ["priority"]=>
  string(0) ""
  ["importance"]=>
  string(0) ""
  ["sensitivity"]=>
  string(0) ""
  ["autoSubmitted"]=>
  string(0) ""
  ["precedence"]=>
  string(0) ""
  ["failedRecipients"]=>
  string(0) ""
  ["subject"]=>
  NULL
  ["fromHost"]=>
  NULL
  ["fromName"]=>
  NULL
  ["fromAddress"]=>
  NULL
  ["senderHost"]=>
  NULL
  ["senderName"]=>
  NULL
  ["senderAddress"]=>
  NULL
  ["to"]=>
  array(0) {
  }
  ["toString"]=>
  NULL
  ["cc"]=>
  array(0) {
  }
  ["bcc"]=>
  array(0) {
  }
  ["replyTo"]=>
  array(0) {
  }
  ["messageId"]=>
  NULL
}

**Additional context**

from the output, it looks almost like it didn't receive any data about the mail message at all?

**Comment by bapcltd-marv** [comment] 2020-02-12 09:12
This may have already been fixed, master branch just appends the attachment whereas develop branch explicitly calls `IncomingMail::setHasAttachments()` after appending the attachment.
https://github.com/barbushin/php-imap/blob/9c1469c053d4f1473cbd3648fc7ae363f6b3aace/src/PhpImap/IncomingMail.php#L81

https://github.com/barbushin/php-imap/blob/94754bb6d6b62cc79a431faeed6d662dd378ff88/src/PhpImap/IncomingMail.php#L108

**Comment by Sebi94nbg** [comment] 2020-05-17 22:04
Closing this issue for now due to no feedback and since nobody else reported or confirmed this issue yet.

**Closed by Sebi94nbg** 2020-05-17 22:04 UTC
Labels: needs investigation

**Comment by bapcltd-marv** [comment] 2020-05-18 08:11
@Sebi94nbg this happened with plain text attachments, although that was more of a #490 issue.
