### ISSUE TITLE
bytes exhausted in Mailbox.php:474

### ISSUE THREAD

**Issue by ghost** [barbushin/php-imap#93] opened 2015-10-08 16:31 UTC
I'm tring to download a lot of files from OUTLOOK.COM but I get a fatal error

My source

https://gist.github.com/BOTERO/8b596693efe489416384

The line

``` php
$data = preg_replace('~[^a-zA-Z0-9+=/]+~s', '', $data); // https://github.com/barbushin/php-imap/issues/88
```

``` php

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65684213 bytes) in /home/ubuntu/workspace/IMAP-Outlook-backup/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 474

Call Stack:
    0.0002     240280   1. {main}() /home/ubuntu/workspace/IMAP-Outlook-backup/index.php:0
  653.0629    2054392   2. PhpImap\Mailbox->getMail() /home/ubuntu/workspace/IMAP-Outlook-backup/index.php:32
  695.5870    2080456   3. PhpImap\Mailbox->initMailPart() /home/ubuntu/workspace/IMAP-Outlook-backup/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:453
  736.0850   34922824   4. preg_replace() /home/ubuntu/workspace/IMAP-Outlook-backup/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:474

```

**Comment by barbushin** [comment] 2015-10-20 22:21
Hi. I can't reproduce this case, but let's try to replace `preg_replace` string with:

```
if(preg_match_all('~[^a-zA-Z0-9+=/]~s', $data, $m, PREG_PATTERN_ORDER)) {
	$str = str_replace($m[0], '', $data);
}
```

Tell me if it works so I'll add this fix in release. Thank you.

**Comment by nettunodev** [comment] 2017-01-30 14:51
I have the same problem, I tried what you suggested but it doesn't work. Do you have other suggestions? Thanks!

**Comment by Sebi94nbg** [comment] 2019-05-01 11:55
Closing this as it's out-dated, the source from gist.github.com does not exist anymore and it depends on the PHP settings (see [memory_limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit)) as well as on the emails, which you fetch.

Feel free to re-open this issue, if you're still facing this issue and need help.

**Closed by Sebi94nbg** 2019-05-01 11:55 UTC
