### ISSUE TITLE
Message Issue

### ISSUE THREAD

**Issue by rfulcher** [barbushin/php-imap#71] opened 2015-03-21 01:32 UTC
I have placed this code in a Codeigniter project.  It has been working good but I have run across one issue that I am not sure how to fix.  I have one message that is not HTML it is plain text and the body of the message is getting dropped.  I would like to fix but I am not well versed in all the parameters and suck with mail & imap.  But what is happening is Line 455 -> 489 pull the body and place it correctly in the $data variable.

After that line $459 shows as having an attachementid.  Once it goes into there the $data is not assigned to anything to be returned.  I see that lines 520 -> 527 is the only place that the $data is assigned to be returned.

I guess my question is, is there an error in the class or is there an error in the mail message?  Should I place an assignment in lines 455 -> 489?  Wondering why there is not one there now.

Thanks very much for your help.

**Comment by rfulcher** [comment] 2015-03-21 01:33
Also there is not an attachment on the email so really it should not be dropping into this if statement at 455.

**Comment by rfulcher** [comment] 2015-03-21 01:46
Ok more info.  Below is what the message has

Content-Type: text/plain; charset="iso-8859-1"
Content-ID: <A2ADC87DD7C6BF4C8D3E6C1A2F9E7B9A@wilson.edu>
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

And the Content-ID is showing up as the attachementid and the ifid is set to 1.  I can't figure out why that would be based on the message source.

Thanks

**Comment by barbushin** [comment] 2015-05-06 19:49
Hi. Could you please forward this mail to barbushin2@gmail.com?

**Comment by Erkens** [comment] 2016-08-02 08:38
The problem is an incorrect mailmessage. Basic example:
```
From: Michael <michael@example.com>
To: Test <test@example.com>
Subject: testmail
Date: Tue, 2 Aug 2016 07:00:00 +0000
Message-ID: <TEST123456ABC-3>
Content-Type: text/plain; charset="us-ascii"
Content-ID: <CONTENTID-BODY>
Content-Transfer-Encoding: quoted-printable

Sample content
```

With imap_fetchstructure you get:

- type = TYPETEXT
- ifid = true
- id= "\<CONTENTID-BODY\>"

Because the "id" php-imap will handle the body as an attachment. Of course this is a bug in the client who send the mail, but when checking the type first (not multipart!) you can ignore the content-id and handle it as a normal body.

**Comment by commanddotcom** [comment] 2018-01-06 13:45
@Erkens , so what is your thoughts on the best solution for multipart email? I've got this kind of emails from LinkedIn: both plain and html gets into attachment and body is NULL?

**Comment by nickl-** [comment] 2019-03-29 12:21
related #39

**Comment by Sebi94nbg** [comment] 2019-05-05 12:33
Fix has been merged.

**Closed by Sebi94nbg** 2019-05-05 12:33 UTC
Labels: need help, question
