### ISSUE TITLE
decodeMimeStr() not expected behaviour

### ISSUE THREAD

**Issue by twmobius** [barbushin/php-imap#530] opened 2020-07-17 10:05 UTC
- PHP IMAP version: 4.1.0
 - PHP Version: 7.2.24
 - Type of execution: CLI

I believe that the removal of the `convertStringEncoding()` method caused by my previous ticket #403, has mixed things up and the expected behaviour by the library with regards to encoding has changed (correct me if I am wrong)

Currently when we try to retrieve the `textHtml` from an email message, php-imap iterates the dataInfo associative array for type `DataPartInfo::TEXT_HTML` and merges the contents of each part under the textHtml variable. 

While doing this, at the end of each `$data->fetch()` it calls `convertEncodingAfterFetch()` which if the charset is set, eventually calls `decodeMimeStr` in order to convert the string where needed.

However the data at this point is not a mime encoded string, but the raw data from the html found in the email. 

`decodeMimeStr` relies on `imap_mime_header_decode()` to detect the encoding. However `imap_mime_header_decode` returns `default` on any non utf-8 string that is not mime encoded. I.e. if you pass an ISO-8859-7 string. (that was my point on #403)

So an ISO-8859-7 encoding html string, never gets converted to utf-8 as was originally expected.

**Comment by twmobius** [comment] 2020-07-17 10:43
Extending `DataPartInfo` and overriding

```
protected function convertEncodingAfterFetch(): string 
{
  if (isset($this->charset) and !empty(\trim($this->charset))) {
    $this->data = $this->mail->decodeMimeStr(
      (string) $this->data, $this->charset
    );
  }

  return (null === $this->data) ? '' : $this->data;
}
```

and extending Mailbox and overriding the `decodeMimeStr` to:

```
public function decodeMimeStr(string $string, ?string $mimeCharset = null): string
{
  $newString = '';
  /** @var list<object{charset?:string, text?:string}>|false */
  $elements = imap_mime_header_decode($string);

  if (false === $elements) {
    return $string;
  }

  foreach ($elements as $element) {
    $charset = ($mimeCharset) ? $mimeCharset : strtolower($element->charset);

    switch ($charset) {
      case 'default': // Charset default is already ASCII (not encoded)
      case 'utf-8': // Charset UTF-8 is OK
        $newString .= $element->text;
      break;
      default:
        // If charset exists in mb_list_encodings(), convert using mb_convert function
        if ( in_array($charset, $this->lowercase_mb_list_encodings())) {
          $newString .= mb_convert_encoding($element->text, 'UTF-8', $charset);
        } else {
          // Fallback: Try to convert with iconv()
          $iconv_converted_string = @iconv($charset, 'UTF-8', $element->text);

          if (!$iconv_converted_string) {
            // If iconv() could also not convert, return string as it is
            // (unknown charset)
            $newString .= $element->text;
          } else {
            $newString .= $iconv_converted_string;
          }
        }
      break;
    }
  }

  return $newString;
}
```

Should work. I don't exactly get what is the point of `decodeMimeStrDefaultCharset`. I get that it works as a fallback but it only makes sense if you are absolutely sure that you will get the email using on charset.

**Comment by bapcltd-marv** [comment] 2020-07-17 11:22
this may be a duplicate of #525

**Comment by twmobius** [comment] 2020-07-17 11:30
@bapcltd-marv Yes, it's the same issue. Feel free to merge the two

**Comment by bapcltd-marv** [comment] 2020-07-17 11:48
ping @Sebi94nbg

**Comment by Sebi94nbg** [comment] 2020-07-27 08:52
Closing this as it's a duplicate of #525.

**Closed by Sebi94nbg** 2020-07-27 08:52 UTC
Labels: duplicate
