### ISSUE TITLE
Smiles\emojis cause damage

### ISSUE THREAD

**Issue by commanddotcom** [barbushin/php-imap#232] opened 2018-03-16 10:58 UTC
I have email subject like:

     =?UTF-8?q?Some_subject_here_?= =?UTF-8?q?=F0=9F=98=98?=

This part `=F0=9F=98=98` is a emoji and it will case error `Mime string encoding conversion failed` in method `convertStringEncoding()` which is called by `decodeMimeStr()`

**Comment by lincome** [comment] 2018-03-21 10:19
Me too.
Does anyone know how to solve emoji problems.

**Comment by Sebi94nbg** [comment] 2019-05-09 19:22
I've added some PHPUnit tests - all is working fine as expected.

The problem is, that you need the server encoding `US-ASCII` with Microsoft Exchange servers and the function `decodeMimeStr()` uses the set server encoding.

So, if you use `US-ASCII` it can not convert emojis or any other UTF8 characters.

So we maybe should just decode such fields like `subject` with UTF8 - even when ASCII is defined?

**Comment by Sebi94nbg** [comment] 2019-05-11 13:25
Fixed with above referenced commit. Will be included in the next release.

**Closed by Sebi94nbg** 2019-05-11 13:25 UTC
Labels: needs investigation, phpunit
