### ISSUE TITLE
.eml file attached with other attachments

### ISSUE THREAD

**Issue by DonCallisto** [barbushin/php-imap#152] opened 2016-06-22 09:37 UTC
As issue title, it's not possibile to fetch mail parts that are email attachments (`partStructure == 2 && partStructure->subtype == 'RFC822'`) that got attachments themselves.

Infact it seems that `imap_fetchbody` returns only a "portion" of requested part, resulting in corrupted files. I've checked with debugger and found that whole attached mail (`.eml`) comes correctly but subparts comes corrupted.

Did you know about this kind of issue?

Any thoughts?

**Comment by pdewit** [comment] 2017-08-03 09:38
I have the same issue, did you end up solving this? @DonCallisto

**Comment by DonCallisto** [comment] 2017-08-21 06:31
@pdewit unfortunately, no

**Comment by LiuHD** [comment] 2017-11-01 07:40
I have the same problem ,if there is any update?

**Comment by DonCallisto** [comment] 2017-11-02 08:03
@LiuHD No, the problem is still there.

Moreover I've recently tried to debug it and I think that's not a library issue but a PHP problem. That's because I've tried "manually" to request a part of the message where the nested attachment is: it results in a bad call and nothing is returned. I've followed the specifications so in my opinion there are two possibile scenario:ù

- PHP Imap (not the library, the PHP implementation itself) is "buggy" (or have a different behavior due to message format) in this particular cases
- Those kind of email does not respect the format and so are "corrupted".

An interesting test that can be done is to parse the same message with another language like python to see if it can parse that email correctly: if so, there's a problem with PHP implementation. If not, there's a problem with email format. 
BTW I didn't had a chance to try it with python but I'll surely do when a buggy message comes again in my application.

**Comment by LiuHD** [comment] 2017-11-03 23:09
Do you have seen the first user contribute note in this page, http://php.net/manual/zh/function.imap-fetchbody.php if not, i think it will be helpful for you.
 I I have tried the same fetch part num generation method it mention, and it surely effect, but the subbody i have got from an eml attachment was encoded in an unknow code

i think the reason is that th subbody was encoded twice,in my test emial, it is encoded twice in base64,  but i can not decode it correctly

thank you!

**Comment by DonCallisto** [comment] 2017-11-04 08:42
@LiuHD I've tried to perform `email_fetchbody()` directly changing by hand the part number as I would have expected them to be (as I said before). The code you linked is used only to "create" the correct parts and their numbers (in our case, this library does it for us); in my case, it seems not to work.
If you suspect that is encoded twice in `base64`, try to decode it twice and see if it works.

Let us know

**Comment by cerwak** [comment] 2018-03-26 12:39
Changing this added condition:
https://github.com/barbushin/php-imap/commit/55e9e243c3be0e4715860eee0e2ca9ac42346dd9
to 
`$partStructure->disposition === "attachment"`
solves this issue. 
Which issue had been resolved in the first place, by adding the condition?

**Comment by Sebi94nbg** [comment] 2019-05-09 07:36
Closing this as it's a duplicate of #278. Please check this issue for the current status.

We're currently working on a solution. But it's still in progress and not fixed yet.

**Closed by Sebi94nbg** 2019-05-09 07:36 UTC
Labels: need help
